version: 2
jobs:
  build:
    
    working_directory: ~/test

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:

      - checkout
      
      - run: mvn package
      - run: mvn test
      
      - store_test_results:
          path: /work/git/teaching-2020.prse.test/target/surefire-reports
          
      - store_artifacts:
          path: /work/git/teaching-2020.prse.test/target/surefire-reports/junit   
